### ISSUE TITLE
Invalid content /en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by cinnl** [cardano-foundation/testnets-cardano-org#136]
**Where does the issue occur?**
https://testnets.cardano.org/en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/ 
The **supported platforms** hyperlink is broken

**Describe the issue**
Hyperlink is broken (https://testnets.cardano.org/enshelley/about/supported-platforms/ should be https://testnets.cardano.org/en/shelley/about/supported-platforms/)

**Expected changes**
`<a lang="en" href="/en/shelley/about/supported-platforms/">supported platforms</a>`

**Comment by olgahryniuk** [comment]
Thank you for your input! PR #454 will fix this issue in due course.
