### ISSUE TITLE
Invalid content /en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by 6cef** [cardano-foundation/testnets-cardano-org#145]
**Where does the issue occur?**
On the Shelley public testnet documentation site.

**Describe the issue**
While following the instructions to install this on an AWS instance, the "build all" step fails.  

**Expected changes**
Not sure.  "stack build all" was a shot in the dark, but does not seem to be the correct command.

**Comment by 6cef** [comment]
It seems the command should perhaps be "stack build all".

**Comment by olgahryniuk** [comment]
We hope you have resolved this issue. Closing this PR, if you encounter any other problems, please reach out to our support team.
