### ISSUE TITLE
Invalid content /en/more/

### ISSUE THREAD

**Issue by Drap3r** [cardano-foundation/testnets-cardano-org#155]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context. 

kevm-testnet.iohkdev.io
https://iele-testnet.iohkdev.io/

**Describe the issue**
A clear and concise description of what the issue is.

Dead links

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by robcohen** [comment]
In the Tools section of https://testnets.cardano.org/en/more/

**Comment by Drap3r** [comment]
https://kevm-testnet.iohkdev.io/

**Comment by Drap3r** [comment]
https://iele-testnet.iohkdev.io/

**Comment by gorgos** [comment]
@robcohen Do those testnets even still exist? I also tried to follow the instructions at https://testnets.cardano.org/en/more/kevm/getting-started/deploying-smart-contracts/ abd the wallet can't connect to the KEVM testnet.

**Comment by Drap3r** [comment]
[image: image.png]

**Comment by olgahryniuk** [comment]
The KEVM content has been recently updated:
https://developers.cardano.org/en/virtual-machines/welcome/
Support and feedback: If you wish to join the dedicated developer program for KEVM, please take our [short survey](https://input-output.typeform.com/c/OJsf0XcD) and we’ll be in touch in due course.
