### ISSUE TITLE
Invalid content /en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by chadnick** [cardano-foundation/testnets-cardano-org#156]
**Where does the issue occur?**
When installing GHC

**Describe the issue**
configure: error: This binary distribution produces binaries for a target with
                  word size of 8, but your target toolchain produces binaries
                  with a word size of 4. Are you sure your toolchain
                  targets the intended target platform of this compiler?

**Complete code as per instructions:**
root@raspberrypi:~# tar -xf ghc-8.6.5-x86_64-deb9-linux.tar.xz
rm ghc-8.6.5-x86_64-deb9-linux.tar.xz
cd ghc-8.6.5                      
./configure
sudo make install
root@raspberrypi:~# rm ghc-8.6.5-x86_64-deb9-linux.tar.xz
root@raspberrypi:~# cd ghc-8.6.5
root@raspberrypi:~/ghc-8.6.5# ./configure
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking target system type... armv7l-unknown-linux-gnueabihf
Build platform inferred as: x86_64-unknown-linux
Host platform inferred as: x86_64-unknown-linux
Target platform inferred as: x86_64-unknown-linux
GHC build  : x86_64-unknown-linux
GHC host   : x86_64-unknown-linux
GHC target : x86_64-unknown-linux
LLVM target: armv7l-unknown-linux-gnueabihf
checking for path to top of build tree... /root/ghc-8.6.5
checking for perl... /usr/bin/perl
checking for a BSD-compatible install... /usr/bin/install -c
checking for gfind... no
checking for find... /usr/bin/find
checking whether ln -s works... yes
checking for gsed... sed
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO C99... none needed
checking for -ld.lld... no
checking for ld.lld... no
checking for -ld.gold... no
checking for ld.gold... ld.gold
checking whether C compiler supports -fuse-ld=gold... yes
checking whether ld is GNU ld... YES
checking whether ld understands --build-id... yes
checking whether ld understands -no_compact_unwind... yes
checking whether ld understands -filelist... no
checking for -strip... no
checking for strip... strip
checking for llc-6.0... no
checking for llc... no
checking for opt-6.0... no
checking for opt... no
checking version of gcc... 8.3.0
checking whether GCC supports -no-pie... yes
checking for extra options to pass gcc when compiling via C...  -fwrapv -fno-builtin
checking Setting up CFLAGS, LDFLAGS, IGNORE_LINKER_LD_FLAGS and CPPFLAGS... done
checking Setting up CONF_CC_OPTS_STAGE0, CONF_GCC_LINKER_OPTS_STAGE0, CONF_LD_LINKER_OPTS_STAGE0 and CONF_CPP_OPTS_STAGE0... done
checking Setting up CONF_CC_OPTS_STAGE1, CONF_GCC_LINKER_OPTS_STAGE1, CONF_LD_LINKER_OPTS_STAGE1 and CONF_CPP_OPTS_STAGE1... done
checking Setting up CONF_CC_OPTS_STAGE2, CONF_GCC_LINKER_OPTS_STAGE2, CONF_LD_LINKER_OPTS_STAGE2 and CONF_CPP_OPTS_STAGE2... done
checking for .subsections_via_symbols... no
checking whether your assembler supports .ident directive... yes
checking for GNU non-executable stack support... no
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void *... 4
configure: error: This binary distribution produces binaries for a target with
                  word size of 8, but your target toolchain produces binaries
                  with a word size of 4. Are you sure your toolchain
                  targets the intended target platform of this compiler?
root@raspberrypi:~/ghc-8.6.5# sudo make install
Makefile:33: *** Please run ./configure first.  Stop.
root@raspberrypi:~/ghc-8.6.5#

**Expected changes**
How to get past this step.

**Additional context**
Thank you for your help!

**Comment by olgahryniuk** [comment]
We hope you have resolved your issue now. Closing this PR, in case you have other questions, please reach out to our support team.
