### ISSUE TITLE
Invalid content /en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by rosario3** [cardano-foundation/testnets-cardano-org#161]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
Download the latest source code from the releases page to **this** folder. After the download has finished, you can check the contents using the following command:

What folder?  How do I download a file i got from internet to my AWS instance?  specific instructions please. 

**Expected changes**
A clear and concise description of what you expected to change.

Better instructions on how to download a file from the internet to my AWS instance. 

**Additional context**

**Comment by CarlosLopezDeLara** [comment]
You may find this useful https://github.com/input-output-hk/cardano-tutorials/tree/master/node-setup

**Comment by olgahryniuk** [comment]
Thank you for your feedback. We hope the above link provided you with the information you were looking for.
Specific AWS instructions can be also found [here](https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/000_AWS.md).
