### ISSUE TITLE
Invalid content /en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by kwigbo** [cardano-foundation/testnets-cardano-org#163]
**Where does the issue occur?**
Download and install GHC section

**Describe the issue**
Using the AWS instructions there was no libtinfo.so.5 in /lib64 which caused a silent issue. Getting to this command "cabal install cardano-node cardano-cli" would result in a failure about determining the version of ghc. Calling --version directly pointed at the missing libtinfo.so.5. Creating a sym link to the existing libtinfo.so.6 seems to have worked. I am a bit new to this and not sure if that will cause any other unexpected issues.

**Comment by CarlosLopezDeLara** [comment]
@nahern I think instruction here use previous version of GHC, its worth taking instructions from  https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html

**Comment by nahern** [comment]
resolved by https://github.com/cardano-foundation/testnets-cardano-org/pull/463
