### ISSUE TITLE
Invalid content /en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by rosario3** [cardano-foundation/testnets-cardano-org#168]
**Where does the issue occur?**
Installing a node using Nix

**Describe the issue**
when following instructions to run a node using Nix, I get "permission denied"

curl https://nixos.org/nix/install > install-nix.sh
./install-nix.sh

**Expected changes**
I would like to know how to get past the permission denied output when installing a node using nix.

**Comment by CarlosLopezDeLara** [comment]
@rosario3 you need to give the install-nix.sh file executable permissions: 

`$ chmod +x install-nix.sh`

@nahern perhaps this step is missing in docs.

**Comment by nahern** [comment]
thank you @CarlosLopezDeLara - will check that step and include if it is missing.

**Comment by rosario3** [comment]
> @rosario3 you need to give the install-nix.sh file executable permissions:
> 
> `$ chmod +x install-nix.sh`
> 
> @nahern perhaps this step is missing in docs.

Got it..works now, thank you!

**Comment by nahern** [comment]
step added to the docs  (https://github.com/cardano-foundation/testnets-cardano-org/pull/465)

**Comment by rosario3** [comment]
Thank you Team.
