### ISSUE TITLE
Invalid content /en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by queiroz** [cardano-foundation/testnets-cardano-org#170]
**Where does the issue occur?**

Followed all the steps to install Cardano node on AWS t2.medium as suggested however when installing haskell compiler I was getting an error when executing `sudo make install`.

The distro is based on RedHat I believe and is known as Amazon 2 AMI.

**Describe the issue**

```
/usr/local/lib/ghc-8.6.5/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
make[1]: *** [install_packages] Error 127
make: *** [install] Error 2
```

**Expected changes**

To fix the issue I had to install `ncurses-compat-libs` which are not mentioned in the documentation however I think it would be beneficial to others if it's introduced on the steps to install haskell compiler.

`sudo yum install ncurses-compat-libs`

**Comment by MDUBY** [comment]
Thanks, it helps.

**Comment by real-tesco** [comment]
Thanks!

**Comment by iostake** [comment]
Thanks a bunch! It finally work after trying it for numerous times! Cardano should include this solution in the documentation

**Comment by matifalcone** [comment]
Thank you so much! 

In my case, it also let GHC installation finish but when I want to check the version I get the following:

`[ec2-user@ip-172-31-41-211 ghc-8.6.5]$ ghc --version
/usr/local/lib/ghc-8.6.5/bin/ghc: /lib64/libtinfo.so.5: no version information available (required by /usr/local/lib
/ghc-8.6.5/bin/../haskeline-0.7.4.3/libHShaskeline-0.7.4.3-ghc8.6.5.so)
/usr/local/lib/ghc-8.6.5/bin/ghc: /lib64/libtinfo.so.5: no version information available (required by /usr/local/lib
/ghc-8.6.5/bin/../ghc-8.6.5/libHSghc-8.6.5-ghc8.6.5.so)
/usr/local/lib/ghc-8.6.5/bin/ghc: /lib64/libtinfo.so.5: no version information available (required by /usr/local/lib
/ghc-8.6.5/bin/../terminfo-0.4.1.2/libHSterminfo-0.4.1.2-ghc8.6.5.so)
The Glorious Glasgow Haskell Compilation System, version 8.6.5`

You can see there are some messages relating `libtinfo.so.5`.

Is this correct anyway?

Thank you,

Matías

**Comment by queiroz** [comment]
@matifalcone if it can't find `libinfo.so` try locating `libinfo.so.5` and create a symlink to it:

locate: 

`ls /usr/lib | grep libtinfo` or `ls /usr/lib64 | grep libtinfo`

then:

`sudo ln -s /path/to/libtinfo.so.5 /path/to/libtinfo.so`

the log should tell you where is looking for `libinfo.so`.

**Comment by olgahryniuk** [comment]
Thank you for raising this issue! This command has been recently updated.
