### ISSUE TITLE
Invalid content /en/shelley/resources/community/

### ISSUE THREAD

**Issue by peytonwinget** [cardano-foundation/testnets-cardano-org#171]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

This issue occurs in two links in the community resources page on the Cardano Testnets page. 

**Describe the issue**
A clear and concise description of what the issue is.

The first issue is the link "Create your own Cardano Haskell node" is a broken link. The second issue is the link under "Testnet stake pool tutorials" is a link that links to bigpey's tutorial playlist. Well this is bigpey and he updated these tutorials for all of the new CLI changes. These tutorials are also much more concise and will help new pool operators more.

**Expected changes**
A clear and concise description of what you expected to change.

Please fix the first broken link that I mentioned. But most importantly update the link with this link "https://www.youtube.com/playlist?list=PLyThQPJpttTJ4r9wUdlWi1DMty4nAT85d", I would also appreciate it if that text was "bigpey's testnet stakepool videos". 

**Additional context**

**Comment by nahern** [comment]
thank you for your feedback, we are resolving this issue, thank you.

**Comment by nahern** [comment]
this has been fixed.
