### ISSUE TITLE
Invalid content /en/shelley/resources/links/

### ISSUE THREAD

**Issue by Kaze-Stake** [cardano-foundation/testnets-cardano-org#173]
**Where does the issue occur?**
https://testnets.cardano.org/en/shelley/resources/links/

**Describe the issue**
There is a typo. "Telegram Shelley testnet and stake pool workhgroup"

**Expected changes**
It's supposed to be "Telegram Shelley testnet and stake pool workgroup"

**Additional context**
Not needed.

**Comment by nahern** [comment]
we are resolving this thank you for your feedback
