### ISSUE TITLE
Invalid content /en/shelley/get-started/creating-a-stake-pool/

### ISSUE THREAD

**Issue by rivinduw** [cardano-foundation/testnets-cardano-org#179]
**Where does the issue occur?**
https://testnets.cardano.org/en/shelley/get-started/creating-a-stake-pool/

**Describe the issue**
Quite a few broken links. 

**Expected changes**
Correct links.

**Additional context**

Places where the links are:

Operational certificates
----------------------
...
...
... See an example of an operational certificate generation here. <https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/node-op-cert.md>
...You can see an example of a transaction containing certificates here. <https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/pool.md>

Stake pool metadata
----------------
...
The registration certificate <https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/pool.md#registering-a-stake-pool>  contains all the necessary information for the execution of the pro

**Comment by olgahryniuk** [comment]
Thank you for your input, the PR #446 provides updated links, the changes will be visible soon
