### ISSUE TITLE
Invalid content /en/shelley/get-started/creating-a-stake-pool/

### ISSUE THREAD

**Issue by IslandPool** [cardano-foundation/testnets-cardano-org#180]
**Where does the issue occur?**
https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/pool.md#registering-a-stake-pool

**Describe the issue**
clicking link to registration certificate

**Expected changes**
would open the correct page

**Additional context**
none

**Comment by olgahryniuk** [comment]
Thank you for your feedback, the links have been recently updated: https://developers.cardano.org/en/testnets/cardano/get-started/creating-a-stake-pool/
