### ISSUE TITLE
Invalid content /en/shelley/about/supported-platforms/

### ISSUE THREAD

**Issue by dmindfuse** [cardano-foundation/testnets-cardano-org#189]
**Where does the issue occur?**
https://testnets.cardano.org/en/shelley/about/supported-platforms/

**Describe the issue**
"It is also possible to run a testnet node on any platform using a virtual machine or Docker image."

**Expected changes**
Docker images are architecture bound. amd64 docker images will not run on aarch64. Hence, the specification of docker images on this page could be rephrased to "...or applicable Docker CPU architecture image"? At least, I advise this until all architectures are supported by Docker images.

**Additional context**
I tried deploying the amd64 docker image on aarch64, which failed.

**Comment by olgahryniuk** [comment]
Thank you for your feedback, the PR for an update is created and changes will be visible after merging.
