### ISSUE TITLE
Invalid content /en/itn/tools/jorvote/

### ISSUE THREAD

**Issue by silversurfer777** [cardano-foundation/testnets-cardano-org#197]
![voteing zip windows](https://user-images.githubusercontent.com/29393827/85922062-2fdeaa80-b8b3-11ea-84de-29430460c7f1.PNG) the windows voting zip does not open after being downloaded 3 separate times. I would expect it to open so that a vote can be made on a windows system
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by silversurfer777** [comment]
![voteing zip windows](https://user-images.githubusercontent.com/29393827/85922133-94016e80-b8b3-11ea-9d85-f6c3d092c688.PNG)

**Comment by olgahryniuk** [comment]
Thank you for your feedback, the ITN environment has been closed several months ago, so closing this issue respectively. We are sorry that this issue hasn't been addressed earlier, please see the latest documentation [here](https://developers.cardano.org/) and contact our support team in case any questions occur.
