### ISSUE TITLE
Invalid content /en/itn/tools/jorvote/ Insllation Error Missing dll

### ISSUE THREAD

**Issue by cmerriamleith** [cardano-foundation/testnets-cardano-org#199]
It would be nice if you provided some basic installation instructions. I unzip the Windows Zip file and click the jorvote.exe and get an error message that VCRUNTIME140_.dll was not found. Reinstalling the program may fix this problem. So what is the fix and were is this dll file located?

**Comment by olgahryniuk** [comment]
Thank you for your feedback, the ITN environment has been closed several months ago, so closing this issue respectively. We are sorry that this issue hasn't been addressed earlier, please see the latest documentation [here](https://developers.cardano.org/) and contact our support team in case any questions occur.
