### ISSUE TITLE
Invalid content /en/shelley/get-started/SP_metadata_register/

### ISSUE THREAD

**Issue by willcbanks** [cardano-foundation/testnets-cardano-org#209]
**Where does the issue occur?**
https://testnets.cardano.org/en/shelley/get-started/SP_metadata_register/

**Describe the issue**
The following line references another page as "Stake Pool Registration" but it's not clear what it is referring to:
3. Register or re-register the pool on-chain using the node CLI as described in the tutorials (Stake Pool Registration). 

**Expected changes**
Please link to the relevant page referred to as '(Stake Pool Registration).'
is it referring to this page? :
"Registering a stake pool on the blockchain" 
https://testnets.cardano.org/en/shelley/get-started/registering-a-stake-pool-on-the-blockchain/

**Additional context**
thats it.

**Comment by olgahryniuk** [comment]
Thank you for your feedback! Yes, that is a correct reference. A PR has been created to add a link to the document, changes will be visible after merging.
