### ISSUE TITLE
Invalid content /en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by cyber-russ** [cardano-foundation/testnets-cardano-org#210]
**Where does the issue occur?**
https://testnets.cardano.org/en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

**Describe the issue**
Item 3 shows the wrong command argument, which has an extra "s" on --nix-extra-conf-files
./install-nix.sh --daemon --nix-extra-conf-files nix.conf

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by nahern** [comment]
this has been updated, thank you for your feedback.

**Comment by nahern** [comment]
resolved by https://github.com/cardano-foundation/testnets-cardano-org/pull/437
