### ISSUE TITLE
Invalid content /en/shelley/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by ghost** [cardano-foundation/testnets-cardano-org#219]
**Where does the issue occur?**
1 - "Installing dependencies"
2 - "How to build and run the node from source"

**Describe the issue**
1 - Documentation does not match that of https://github.com/input-output-hk/cardano-node/blob/master/README.md:
- missing dependency libsodium
- build flags related to libsodium not meti
2 - Misleading "git clone" then "Download the latest source code from the releases page" instructions.
If one has already cloned the project, no need to download the source.
Rather "Get the latest release tag x.y.z from the releases page" then "git checkout tags/x.y.z"

**Comment by CarlosLopezDeLara** [comment]
@nahern  Track it together with https://github.com/cardano-foundation/testnets-cardano-org/issues/459

**Comment by nahern** [comment]
this has been resolved by https://github.com/cardano-foundation/testnets-cardano-org/pull/463

**Comment by nahern** [comment]
closing issue, as PR for changes has been merged.
