### ISSUE TITLE
Invalid content /en/shelley/get-started/SP_metadata_register/

### ISSUE THREAD

**Issue by m3ntat** [cardano-foundation/testnets-cardano-org#227]
**Where does the issue occur?**

https://testnets.cardano.org/en/shelley/get-started/SP_metadata_register/

In step 3 @ Signing the transaction.

**Describe the issue**

Signing-key is duplicated. the second one should be stake.skey

cardano-cli shelley transaction sign \
--tx-body-file tx.raw \
--signing-key-file payment.skey \
--signing-key-file payment.skey \
--signing-key-file cold.skey \
--testnet-magic 42 \
--out-file tx.signed

**Expected changes**

cardano-cli shelley transaction sign \
--tx-body-file tx.raw \
--signing-key-file payment.skey \
--signing-key-file stake.skey \
--signing-key-file cold.skey \
--testnet-magic 42 \
--out-file tx.signed

**Additional context**

**Comment by olgahryniuk** [comment]
Thank you for your input, PR #456 addresses these changes, which will be visible after merging.
