### ISSUE TITLE
Invalid content /en/shelley/get-started/SP_metadata_register/

### ISSUE THREAD

**Issue by GBrito93** [cardano-foundation/testnets-cardano-org#230]
On the tutorial to build and configure a stake pool, the metadata-hash command is not valid. Can't continue to create my stake pool....

Command that's invalid:
cardano-cli shelley stake-pool metadata-hash --pool-metadata-file testPool.json

Thanks

**Comment by olgahryniuk** [comment]
Thank you for your feedback. PR 456 addresses this issue, also, please see the latest documentation here:
https://github.com/input-output-hk/cardano-node/blob/master/doc/stake-pool-operations/register_stakepool.md
