### ISSUE TITLE
Invalid content /en/shelley/get-started/creating-a-stake-pool/

### ISSUE THREAD

**Issue by sshine** [cardano-foundation/testnets-cardano-org#232]
**Where does the issue occur?**
Broken link on this page: https://testnets.cardano.org/en/shelley/get-started/creating-a-stake-pool/

In this sentence:

> *[...]* See an example of an operational certificate generation [here][broken-link].

[broken-link]: https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/node-op-cert.md

**Describe the issue**
A link to a piece of tutorial documentation is unavailable because the GitHub repository structure changed:

https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup

It appears that tutorial pages were prefixed with a number, but also, this exact file does not appear to exist, so probably it was renamed.

**Expected changes**
Change the broken link to that .md file in the repository that fits best. Probably there is an exact fit.

**Additional context**
None.

**Comment by olgahryniuk** [comment]
Thank you for raising this issue! The links have been recently updated here:
https://developers.cardano.org/en/testnets/cardano/get-started/creating-a-stake-pool/
