### ISSUE TITLE
Invalid content /en/shelley/tools/staking-calculator/

### ISSUE THREAD

**Issue by pelote23** [cardano-foundation/testnets-cardano-org#233]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment]
Thanks for raising an issue. Unfortunately, it is not clear from the above what an issue is. 
The Staking Calculator page is working and updated:
https://developers.cardano.org/en/testnets/cardano/tools/staking-calculator/
