### ISSUE TITLE
Invalid content in Tools menu...

### ISSUE THREAD

**Issue by mark-stopka** [cardano-foundation/testnets-cardano-org#235]
Dashboard link is pointing to invalid address...

![image](https://user-images.githubusercontent.com/18139116/87803846-632dad00-c853-11ea-9d38-6d6a22052e6c.png)

![image](https://user-images.githubusercontent.com/18139116/87803947-7c365e00-c853-11ea-89bd-c315073e6a79.png)

**Comment by olgahryniuk** [comment]
Thank you for your input, the website navigation has been changed. Now all the links are working:
Faucet: https://developers.cardano.org/en/testnets/cardano/tools/faucet/ 
Dashboard: https://monitoring.cardano-testnet.iohkdev.io/grafana/d/Oe0reiHef/cardano-application-metrics-v2?orgId=1&refresh=1m&from=now-2d&to=now 
Staking calculator: https://developers.cardano.org/en/testnets/cardano/tools/staking-calculator/
