### ISSUE TITLE
I was asked to complete a recapcha and there was no recapcha to complete. Invalid content /en/shelley/tools/faucet/

### ISSUE THREAD

**Issue by ReedBurch** [cardano-foundation/testnets-cardano-org#237]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by ReedBurch** [comment]
https://testnets.cardano.org/en/shelley/tools/faucet/
I was requesting faucet funds and it came up with a request to complete the recapcha, but there was no recapcha. I tried resetting it and got the same response again.

**Comment by CarlosLopezDeLara** [comment]
@nahern Looks good here: https://developers.cardano.org/en/testnets/cardano/tools/faucet/ 

Can close

**Comment by nahern** [comment]
thanks @CarlosLopezDeLara - closing
