### ISSUE TITLE
Invalid content /en/shelley/get-started/pledging-and-rewards/

### ISSUE THREAD

**Issue by kaprijela** [cardano-foundation/testnets-cardano-org#246]
**Where does the issue occur?**
https://testnets.cardano.org/en/shelley/get-started/pledging-and-rewards/
![Screenshot_20200723_005530](https://user-images.githubusercontent.com/20001657/88237291-45ab7980-cc7f-11ea-8c02-5879a55827b4.png)

**Describe the issue**
The **pledge formula** which specifies how the _"share of all available rewards that a specific pool can receive is determined"_ does not show properly, since the image link references the image in the github repository instead of the raw file.

**Expected changes**
The image link ought to be changed from `https://github.com/cardano-foundation/testnets-cardano-org/blob/staging/resources/content/articles/article-images/pledge_formula.png` to (perhaps?) `https://raw.githubusercontent.com/cardano-foundation/testnets-cardano-org/staging/resources/content/articles/article-images/pledge_formula.png`.

**Additional context**
None is necessary, I believe.

**Comment by olgahryniuk** [comment]
@iamrobertmoore will you please take a look at this one? The image shows in the GH repo:
https://github.com/cardano-foundation/testnets-cardano-org/blob/staging/resources/content/articles/en/2020-05-05_15-48-49_pledging-and-rewards-en.md

**Comment by iohkwebdev** [comment]
@olgahryniuk fixed on staging - will go live in next push to master.
