### ISSUE TITLE
Invalid content /en/cardano/get-started/creating-a-stake-pool/

### ISSUE THREAD

**Issue by MrMaik** [cardano-foundation/testnets-cardano-org#271]
**Where does the issue occur?**
https://testnets.cardano.org/en/cardano/get-started/creating-a-stake-pool/

**Describe the issue**
The links contained in the "Operational certificates" and "Public stake pools" sections don't work.

**Expected changes**
I expected to be taken to the relevant pages, instead I got to see the github 404 page

**Comment by olgahryniuk** [comment]
Thank you for your input, this issue is being resolved in #446
