### ISSUE TITLE
Invalid content /en/cardano/about/the-testnet-faucet/

### ISSUE THREAD

**Issue by pelote23** [cardano-foundation/testnets-cardano-org#272]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment]
Unfortunately, it is not clear what the issue details are. The faucet page is working:
https://developers.cardano.org/en/testnets/cardano/tools/faucet/
If you encounter any issues, please provide a clear and concise description of what the issue is.
