### ISSUE TITLE
Invalid content /en/cardano/tools/faucet/

### ISSUE THREAD

**Issue by ThaiTheo** [cardano-foundation/testnets-cardano-org#275]
This page
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

Address to return tokens to is wrong.
A clear and concise description of what the issue is.

An address that resides on testnet
A clear and concise description of what you expected to change.

**Additional context**

cardano@1producer1:~/cardano-testnet$ cardano-cli shelley transaction build-raw \
> --tx-in 1f5bc3a72c35ac6c87a080e21266bcc3fad2a194b8b079f06683c3432a2b7621#0 \
> --tx-in f382c812ed0a30f8bb513e3b933163ae59f63fb5eab8da5162c5695e2aee0e56#0 \
> --tx-out addr1qqr585tvlc7ylnqvz8pyqwauzrdu0mxag3m7q56grgmgu7sxu2hyfhlkwuxupa9d5085eunq2qywy7hvmvej456flknsug829n+497112479 \
> --ttl 2466220 \
> --fee 17000 \
> --out-file tx.raw
option --tx-out: Failed reading: invalid address

**Comment by nahern** [comment]
thank you for your feedback, am checking with the development team on this and will confirm.

**Comment by CarlosLopezDeLara** [comment]
Looks good here: https://developers.cardano.org/en/testnets/cardano/tools/faucet/ 

Can close.

**Comment by nahern** [comment]
thank you for confirming all is working properly @CarlosLopezDeLara - closing this issue.
