### ISSUE TITLE
Invalid content /en/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by srishti-monali** [cardano-foundation/testnets-cardano-org#276]
**Where does the issue occur?**
on running
>nix-build -A scripts.ff.node -o ff-node-local 

**Describe the issue**
```
trace: Using IOHK default nixpkgs
error: attribute 'ff' in selection path 'scripts.ff.node' not found
```
**Expected changes**
I think we must have some file having testnet/shelley or so in the script name

**Comment by degeezz** [comment]
Hi, is there a resolution for this? I get the exact same error from a new setup of Ubuntu 20.04.2 LTS

**Comment by CarlosLopezDeLara** [comment]
@nahern ff was friends and family testnet (when testing shelley) now the command should be: 

nix-build -A scripts.testnet.node -o testnet-node

note here: @degeezz

**Comment by nahern** [comment]
thanks @CarlosLopezDeLara - will amend
