### ISSUE TITLE
Invalid content /en/marlowe/overview/ : Wrong Payee in static analysis example

### ISSUE THREAD

**Issue by vincedjango** [cardano-foundation/testnets-cardano-org#277]
**Where does the issue occur?**
In Section 12.1 of the Marlowe [documentation](https://alpha.marlowe.iohkdev.io/tutorial/#static-analysis)

**Describe the issue**
The example shown in the documentation is explained here:
`The contract first requires a deposit from Alice of 1 Lovelace, and then asks Bob to make a choice (called bool) of 0 or 1. The contract then pays this choice plus one to Bob from Alice’s account.
`

In this example, the Pay section shows that the payee is _Alice_, but the text explains that the payee is supposed to be _Bob_, but in _Blocky_ and the _Haskel_ code, the payee is set to Alice. It should be changed to _Bob_.

**Expected changes**
The blocky diagram should be changed to Bob as shown in this image
![Chapter 12 Error Marlowe](https://user-images.githubusercontent.com/15255728/90364367-10ddd880-e019-11ea-8fc6-eb8a91733961.png)

The pure Marlowe section:
Line 24 should be: `(Role "bob")`

**Comment by nahern** [comment]
thank you for your feedback. I have raised this with the development team and they have created a ticket to update this in the tutorial.

**Comment by nahern** [comment]
this has been resolved, see: https://alpha.marlowe.iohkdev.io/tutorial/index.html#static-analysis
