### ISSUE TITLE
Invalid content /en/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by aminems** [cardano-foundation/testnets-cardano-org#281]
**Where does the issue occur?**
Typo in this command : ./install-nix.sh --daemon --nix-extra-conf-files nix.conf 
The correct one is : ./install-nix.sh --daemon --nix-extra-conf-file nix.conf 

**Describe the issue**
There is a typo at the command option nix-extra-files. file instead of files

**Expected changes**
 ./install-nix.sh --daemon --nix-extra-conf-file nix.conf 

**Additional context**
none

**Comment by olgahryniuk** [comment]
Thank you, this issue has been resolved and the page is to be updated shortly.
