### ISSUE TITLE
Invalid content /en/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by s4cha** [cardano-foundation/testnets-cardano-org#282]
A typo seems to have slipped in the nix install documentation :
https://testnets.cardano.org/en/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

`--nix-extra-conf-files` -> `--nix-extra-conf-file`

**Comment by nahern** [comment]
Hi @CarlosLopezDeLara - could you please validate this before I update, thank you.

**Comment by CarlosLopezDeLara** [comment]
@nahern  Oh yeah! It looks like we have an extra 's'.  It should read:

`--nix-extra-conf-file`

just as @s4cha pointed.

**Comment by olgahryniuk** [comment]
Closing the issue as it has been resolved. Thank you!
