### ISSUE TITLE
Invalid Marlowe tutorial link /en/marlowe/resources/links/

### ISSUE THREAD

**Issue by DamjanOstrelic** [cardano-foundation/testnets-cardano-org#283]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

https://testnets.cardano.org/en/marlowe/resources/links/

**Describe the issue**
A clear and concise description of what the issue is.
Marlowe Tutorial link returns:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>tutorial</Key>
<RequestId>81842F5028A8A4A9</RequestId>
<HostId>l/pejS0BpLGNYDXC0rmF9hlWBcTtRj6aup1f79dMFRmLRNeqz9shKQK3Gau5ni13KNJfGyFFgNA=</HostId>
</Error>
```
**Expected changes**
A clear and concise description of what you expected to change.

Fix the link from `https://alpha.marlowe.iohkdev.io/tutorial` to `https://alpha.marlowe.iohkdev.io/tutorial/index.html`
**Additional context**

**Comment by nahern** [comment]
closing this PR as link navigates to the up to date Marlowe playground tutorial.
