### ISSUE TITLE
Docker image for cardano node

### ISSUE THREAD

**Issue by mesudip** [cardano-foundation/testnets-cardano-org#284]
I will be involved in a project involving cardano in coming days. I will eventually have to containerize the cardano node, so I wanted to express my interest to add a contribution here.

- [ ] Create `Dockerfile` for image with default settings
- [ ] Add script to read configuration options from environment variables.
- [ ] Setup CI for automatic update on hub.docker.com

**Comment by pascalandy** [comment]
Following! I'm interested to host a node using Docker as well :-)

**Comment by Katekko** [comment]
> Following! I'm interested to host a node using Docker as well :-)
> I found this repo via the docs: https://testnets.cardano.org/en/cardano/get-started/installing-and-running-the-cardano-node/running-the-node-using-docker/

Clicking in this link I'm being redirected to https://developers.cardano.org/

**Comment by robinboening** [comment]
Only the subdomain is different, try this linke instead: https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/running-the-node-using-docker/

**Comment by robinboening** [comment]
Maybe its worth mentioning there is an official docker image at dockerhub https://hub.docker.com/r/inputoutput/cardano-node

**Comment by pascalandy** [comment]
@robinboening thank you. Any instructions about the configs?

**Comment by mesudip** [comment]
@pascalandy If you are familiar with docker-compose, Here is an example 

https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml

**Comment by pascalandy** [comment]
Thank you @mesudip ! Yes I am and I run many things in prod using docker, compose and stacks :)

Now, where do we find all the configs to set up ? The obvious one would be ENV_WALLET_ADDRESS. I'm sure there is more. 

Thanks again

**Comment by jdbohrman** [comment]
@mesudip With respect, I think the issuse that @pascalandy is trying to express is that your documentation has no real information regarding environment variables or configurations. This is a real issue I've noticed with this project and it really affects developer adoption.

**Comment by olgahryniuk** [comment]
Please also check some details here > https://docs.cardano.org/getting-started/installing-the-cardano-node
We'd appreciate it if you could raise development issues directly in this repository:
https://github.com/input-output-hk/cardano-node/tree/master/doc/getting-started
