### ISSUE TITLE
Invalid content /en/marlowe/getting-started/sample-marlowe-smart-contracts/

### ISSUE THREAD

**Issue by chillyistkult** [cardano-foundation/testnets-cardano-org#286]
**Where does the issue occur?**
https://testnets.cardano.org/en/marlowe/getting-started/sample-marlowe-smart-contracts/

**Describe the issue**
Both links "[section 3](https://alpha.marlowe.iohkdev.io/tutorial/#escrow-ex)" and "[section 13](https://alpha.marlowe.iohkdev.io/tutorial/#actus-marlowe)" on this page are broken.

`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>tutorial</Key>
<RequestId>81842F5028A8A4A9</RequestId>
<HostId>l/pejS0BpLGNYDXC0rmF9hlWBcTtRj6aup1f79dMFRmLRNeqz9shKQK3Gau5ni13KNJfGyFFgNA=</HostId>
</Error>`

**Expected changes**
Fix the links to the sample contracts.

**Comment by olgahryniuk** [comment]
These links were recently fixed, thank you for your input.
