### ISSUE TITLE
Invalid content /en/marlowe/getting-started/using-the-marlowe-playground/

### ISSUE THREAD

**Issue by jeroendeweerd** [cardano-foundation/testnets-cardano-org#291]
**Where does the issue occur?** -> https://alpha.marlowe.iohkdev.io/tutorial is broken.
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue** -> The link to the tutorial does not word, seems broken.
A clear and concise description of what the issue is.

**Expected changes** -> make the correct link
A clear and concise description of what you expected to change.

**Additional context** -> more links on that Marlow page do not work.

**Comment by nahern** [comment]
closing this issue as link navigates to the up to date playground.
