### ISSUE TITLE
Invalid content /en/marlowe/resources/links/

### ISSUE THREAD

**Issue by Montanajim** [cardano-foundation/testnets-cardano-org#292]
**Where does the issue occur?**
Invalid content /en/marlowe/resources/links/

**Describe the issue**
The Marlowe Tutorial Link is broken.  When you click on it, it takes you to this page which has nothing on it except som broken xml.  https://alpha.marlowe.iohkdev.io/tutorial

**Expected changes**
I expected to see a tutorial on Marlowe.

**Additional context**

**Comment by olgahryniuk** [comment]
This link has been fixed, thank you for your input.
