### ISSUE TITLE
Invalid content /en/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by Blacksheep70** [cardano-foundation/testnets-cardano-org#294]
**Where does the issue occur?**
https://testnets.cardano.org/en/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

**Describe the issue**
Command
`./install-nix.sh --daemon --nix-extra-conf-files nix.conf`
is wrong (`--nix-extra-conf-files` is wrong -> it is `--nix-extra-conf-file` instead)

**Expected changes**
Replace
`./install-nix.sh --daemon --nix-extra-conf-files nix.conf`
with
`./install-nix.sh --daemon --nix-extra-conf-file nix.conf`

**Comment by nahern** [comment]
thank you for your feedback, this has been updated.

**Comment by nahern** [comment]
resolved by https://github.com/cardano-foundation/testnets-cardano-org/pull/437
