### ISSUE TITLE
Invalid content /en/cardano/get-started/configuring-a-node-using-yaml/

### ISSUE THREAD

**Issue by Padierfind** [cardano-foundation/testnets-cardano-org#297]
**Where does the issue occur?**
https://testnets.cardano.org/en/cardano/get-started/configuring-a-node-using-yaml/

The "README file" link at the bottom of the page right above the "Previous"-button.

**Describe the issue**
The link to the README file leads to an empty github page. 

**Expected changes**
Change the link

**Additional context**

**Comment by olgahryniuk** [comment]
Thank you for your feedback
