### ISSUE TITLE
Invalid content /en/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by tonypius** [cardano-foundation/testnets-cardano-org#298]
**Where does the issue occur?**
Download and install GHC section.

**Describe the issue**
While installing, the GHC install process throws this error 
" usr/local/lib/ghc-8.6.5/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file o "

**Expected changes**
To correct this install "sudo yum install ncurses-compat-libs"

**Comment by olgahryniuk** [comment]
Thank you for your input
