### ISSUE TITLE
Documentation for build from source has a missing dependency

### ISSUE THREAD

**Issue by ansco11** [cardano-foundation/testnets-cardano-org#338]
Documentation: missing dependency for Ubuntu 20.04

When installing from source using the link:

https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

`cabal install cardano-node cardano-cli` fails for cardano-node 1.24.2

Fixed with: `apt install libsodium-dev` and adding these lines to cabal.project

```
package cardano-crypto-praos
  flags: -external-libsodium-vrf
```

**Comment by CarlosLopezDeLara** [comment]
@niamh this is related to outdated installation instructions. We can close the issue once the instructions are correctly picked from https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html

thanks @ansco11

**Comment by nahern** [comment]
instructions now point to latest, thanks for your feedback @ansco11

**Comment by nahern** [comment]
resolved by https://github.com/cardano-foundation/testnets-cardano-org/pull/463
