### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by marktaha** [cardano-foundation/testnets-cardano-org#363]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/
**Describe the issue**
A clear and concise description of what the issue is.
The link in "Supported Platforms" in the 2nd paragraph goes to a missing page https://developers.cardano.org/en/cardano/about/supported-platforms/. 404 error.
**Expected changes**
A clear and concise description of what you expected to change.
create missing page or fix link.
**Additional context**

**Comment by olgahryniuk** [comment]
Thank you for your feedback!
