### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

### ISSUE THREAD

**Issue by Nidhoggr** [cardano-foundation/testnets-cardano-org#374]
**Where does the issue occur?**
All reference links on https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

- Building a node using Nix
- Building a node from source
- Running a node using Docker
- Running a node on an AWS instance

Returns a 404 error

**Comment by olgahryniuk** [comment]
This issue is now fixed, thank you for your feedback
