### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

### ISSUE THREAD

**Issue by EmreCem** [cardano-foundation/testnets-cardano-org#378]
At the bottom of "https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/"

![Screenshot_1](https://user-images.githubusercontent.com/32422460/102607634-a7421800-4139-11eb-81f0-aa5b6342f563.jpg)

These links leads to wrong path (missing "/testnets/)

For example:
"https://developers.cardano.org/en/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/"
should be changed to:
"https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/"

Each link listed on the page has this issue.

**Comment by olgahryniuk** [comment]
This issue is now fixed, thank you!
