### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by joachimlindback** [cardano-foundation/testnets-cardano-org#382]
I also needed a file cabal.project.local with following two lines as content (FreeBSD 12.2, libsodium installed with package manager).
package cardano-crypto-praos
flags: -external-libsodium-vrf

**Comment by CarlosLopezDeLara** [comment]
@nahern Let's make sure we pick instructions from https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html so that this docs don't get outdated. 

Thanks @joachimlindback

**Comment by nahern** [comment]
thanks @CarlosLopezDeLara - will update that to point to the https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html instructions which will always be up to date.

**Comment by nahern** [comment]
resolved by https://github.com/cardano-foundation/testnets-cardano-org/pull/463
