### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

### ISSUE THREAD

**Issue by Sokos6** [cardano-foundation/testnets-cardano-org#385]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

**Describe the issue**
On the Installing and running a Cardano Node page, the link for Nix goes to page not found. 

**Expected changes**
https://developers.cardano.org/en/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/
This link should go to the documentation for using Nix.

**Comment by olgahryniuk** [comment]
This issue is now resolved, thank you for your feedback
