### ISSUE TITLE
Invalid content /en/virtual-machines/FAQ_kevm_iele/

### ISSUE THREAD

**Issue by jonassunandar** [cardano-foundation/testnets-cardano-org#391]
**Where does the issue occur?**
When I was learning about new interesting updates in Cardano I found out that there are some broken link in the [FAQ for KEVM & IELE](https://developers.cardano.org/en/virtual-machines/FAQ_kevm_iele/)

**Describe the issue**
Here is the two broken links that I spotted. Please click the link below to see the problem

- Q. What’s the user journey of what a developer can do, step by step, using what tools?
 A. You can read the [Smart Contracts Architecture ](http://../iele_vm_architecture)article, and see how the different pieces work together.

- Q. What’s Mallet, and how does it fit into the journey?
   A. Mallet, the minimal wallet, is the [command line interface ](https://developers.cardano.org/en/virtual-machines/kevm/getting-started/deploying-smart-contracts/)used to send transactions, deploy smart contracts, and interact with the IELE and KEVM devnets.

**Expected changes**
Please update the link to the newest one. I would love to help by creating PR, however I couldn't find the links that should be there

thank you guys. Keep up the good work

**Comment by olgahryniuk** [comment]
thank you for your feedback
