### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

### ISSUE THREAD

**Issue by gleize** [cardano-foundation/testnets-cardano-org#392]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

**Describe the issue**
All four links are broken (page not found).

**Expected changes**
Proper links.

**Additional context**
None.

**Comment by olgahryniuk** [comment]
This issue is now resolved, thank you for your feedback.
