### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

### ISSUE THREAD

**Issue by iasinDev** [cardano-foundation/testnets-cardano-org#395]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

**Describe the issue**
Hyperlinks of the 4 ways of building a node are broken; the target destination pages, in fact, exists, but are not correctly codified the url's in the hyperlinks

**Expected changes**
Fix the following 4 hyperlinks to the correct urls

Building a node using Nix
Building a node from source
Running a node using Docker
Running a node on an AWS instance

**Comment by iasinDev** [comment]
Solved [here](https://github.com/cardano-foundation/testnets-cardano-org/pull/396)

**Comment by olgahryniuk** [comment]
Thank you for your feedback, the above links were fixed, and one remaining is being fixed in PR #440
