### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by helpium** [cardano-foundation/testnets-cardano-org#397]
**Describe the issue**
--nix-extra-conf-files is wrong
./install-nix.sh --daemon --nix-extra-conf-files nix.conf

correct: ./install-nix.sh --daemon --nix-extra-conf-file nix.conf

**Comment by olgahryniuk** [comment]
Thank you for your feedback, resolved in PR #437
