### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

### ISSUE THREAD

**Issue by thisismytofu** [cardano-foundation/testnets-cardano-org#399]
**Where does the issue occur?**
/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

**Describe the issue**
Every link on this page points to a "Page not found" page.

**Expected changes**
Pages should exist...

**Comment by olgahryniuk** [comment]
Thank you for your feedback!

**Comment by thisismytofu** [comment]
Why did you close this...? The links are still broken...

**Comment by olgahryniuk** [comment]
@thisismytofu, when we visit the [following page ](https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/), all the four links are working:
Building a node using Nix
Building a node from source
Running a node using Docker
Running a node on an AWS instance

The 'supported platforms' link has been fixed a few hours ago, and the PR is merged into staging. These changes will be live and visible by tomorrow.

**Comment by thisismytofu** [comment]
Ah cool, works now, thanks! (and sorry for having been impatient with my first reply...) :)

**Comment by olgahryniuk** [comment]
No worries, thanks for your time and input :)
