### ISSUE TITLE
Invalid content /en/virtual-machines/kevm/resources/support-and-help/

### ISSUE THREAD

**Issue by SL13PNIR** [cardano-foundation/testnets-cardano-org#403]
**Where does the issue occur?**
On the following page: [https://developers.cardano.org/en/virtual-machines/kevm/resources/support-and-help/](https://developers.cardano.org/en/virtual-machines/kevm/resources/support-and-help/) 

See the following link under the support and help heading:

You can also **[Join IOHK | Devnets on Slack](https://join.slack.com/t/iohkdevnets/shared_invite/zt-jvy74l5h-Bhp5SQajefwjig72BIl73A) **, where the community and IOG developers share their experience.

**Describe the issue**
The slack invitation doesn't work.

**Expected changes**
Renew the invitation.

**Comment by SL13PNIR** [comment]
Link has since been updated but is restricted to runtime verification email addresses, message states to contact workspace admin, but the 'contact us' link requires sign in so user is face with 'chicken or the egg' scenario:

![image](https://user-images.githubusercontent.com/19766122/104820286-ae893e00-582b-11eb-8659-7d72a13c6a73.png)

**Comment by SL13PNIR** [comment]
@olgahryniuk Do you know who is responsible for this repository and maintaining the Cardano site?

I'm a Cardano Ambassador and I've got devs interested in the devnets but they are [reporting these issues on reddit](https://www.reddit.com/r/CardanoDevelopers/comments/kymkyr/devnet_slack_access/), it would good if we could get these types of issues resolved quickly, however issues aren't being closed here. Is there a better place to report them (or even fixed them myself)?

**Comment by olgahryniuk** [comment]
Thank you for contacting us @SL13PNIR!
Please fill out the survey form here https://input-output.typeform.com/to/OJsf0XcD and our team will send you an invitation link to the Slack channel. 
We will be updating the 'support and help' page for better clarity in the due course.
Kind regards

**Comment by SL13PNIR** [comment]
@olgahryniuk Thanks for the update, I'll let them know.

**Comment by olgahryniuk** [comment]
Thanks, Kai! The 'Support and Help' page is now updated: https://developers.cardano.org/en/virtual-machines/kevm/resources/support-and-help/
