### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by greerben0** [cardano-foundation/testnets-cardano-org#414]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

**Describe the issue**
Instruction number 3 has an extra 's' in the command.`nix-extra-conf-files` should not be plural

**Expected changes**
Change `./install-nix.sh --daemon --nix-extra-conf-files nix.conf` to `./install-nix.sh --daemon --nix-extra-conf-file nix.conf`

**Comment by nahern** [comment]
thank you for your feedback, will amend this command.
