### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/registering-a-stake-pool-on-the-blockchain/

### ISSUE THREAD

**Issue by devcflynn** [cardano-foundation/testnets-cardano-org#438]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/registering-a-stake-pool-on-the-blockchain/

**Describe the issue**
Output formatting is broken halfway through the article causing display issues around this section:
` > 171485
In addition to paying fees for this transaction, you also need to include a deposit. This deposit is refundable and you will get it back when you deregister the key. The deposit amount can be found in the protocol.json under key keyDeposit:
...
 "keyDeposit": 400000,
 …`

**Expected changes**
Hopefully, the documentation gets edited to be formatted correctly and less confusing

**Additional context**
There seems to be missing content or context around the commands. It is not very obvious on a step by step basis what is actually happening nor how I should get some of the params to use in the command.

**Comment by olgahryniuk** [comment]
Thank you for your feedback, a new PR has been created to address this issue.
