### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by redsharpbyte** [cardano-foundation/testnets-cardano-org#459]
**Where does the issue occur?**

*Short answer, here:* https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

*Long answer, with user flow:* When on main page cardano.org I was one visitor following that track:
 - Developers (menu) > Stake Pool Operation : https://cardano.org/stake-pool-operation/
 - Mid nav bar > Set up Stake Pool: https://cardano.org/stake-pool-operation#set-up-stake-pool
 - "Interested in developing on the Cardano platform or running a stake pool?" clicked on the button `Learn how` > (new tab opens) https://developers.cardano.org/
 - Use the button on bottom of first page `Find out more`: https://developers.cardano.org/en/testnets/cardano/overview/
 - THen using the menu on side bar (left) to get on the install from source guide which is the link mentioned all above: "Getting Started" > "Installing and running a... node..." > "... form source": https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

**Describe the issue**
This installation from source there will not work, there are critical missing information about the necessary custom installation of libsodium (https://github.com/input-output-hk/libsodium) that includes verifiable random functions (VRF) not (yet :) ) in upstream.

As well as how to set cabal to use that externally installed library (libsodium).

**Expected changes**
Redirect to the correct documentation, which is git tracked and coherent with the node sources: 
https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html

**Additional context**
I found out through the forum posts this happened to a lot of people and the developers.cardano.org might be misleading a lot of people, while docs.cardano.org should be the reference.

This would certainly solve following open issues:
#382 
#338 
#219 

Unfortunately users there did not all mention the exact information page they tried to follow installation procedure but I can surely suppose it was on developers.cardano.org .

**Comment by CarlosLopezDeLara** [comment]
@nahern , @redsharpbyte is right. instructions on https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/ are outdated. 

We should pick instructions from https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html 

We can close this issue once it is on your backlog.

**Comment by nahern** [comment]
resolved by https://github.com/cardano-foundation/testnets-cardano-org/pull/463
