### ISSUE TITLE
vague content /en/testnets/cardano/get-started/creating-a-stake-pool/

### ISSUE THREAD

**Issue by tomschneider** [cardano-foundation/testnets-cardano-org#460]
**Where does the issue occur?**
It occurs in this statement which is now being propagated in 'how to' videos.

"a good network connection and about 1 GB of bandwidth per hour"

**Describe the issue**
Bandwidth is a two way street. Inbound bandwidth, outbound bandwidth or a combination?  Which is it, is my question.

**Expected changes**
I would expect the definition of 1 GB of bandwidth per hour describe precisely the requirements with respect to inbound/ingress or outbound/egress.

So, with respect to a Stake Pool Node, is bandwidth inbound or outbound - there should be two values, not one.

Example from Azure VM docs:
_The network bandwidth allocated to each virtual machine is metered on egress (outbound) traffic from the virtual machine._

**Additional context**
From my experience, network bandwidth is **not ever defined in bandwidth per hour**, but in bandwidth per second, such as Megabits per second, aka Mbps.

I would recommend that your documentation team recalculate ingress and egress bandwidth requirements in Mbps unit of measure.

Example from Azure VM docs:
_Azure offers a variety of VM sizes and types, each with a different mix of performance capabilities. One capability is network throughput (or bandwidth), measured in megabits per second (Mbps)._

Thanks, Tom Whitehill

**Comment by olgahryniuk** [comment]
Thank you for your input. We suggest raising this issue directly in the development repository > https://github.com/input-output-hk/cardano-node#network-configuration-genesis-and-topology-files
