### ISSUE TITLE
Invalid content /en/testnets/cardano/tools/faucet/

### ISSUE THREAD

**Issue by dgellow** [cardano-foundation/testnets-cardano-org#473]
After requesting ADA for the testnet a link to check the transaction is generated. The link is something like https://cardano-explorer.cardano-testnet.iohkdev.io/tx/<YOUR_TRANSACTION>. That doesn't seem to be correct as I get an issue from the TLS certificate.

Looking at the actual common name of the certificate I see that the link should instead be https://explorer.cardano-testnet.iohkdev.io/tx/<YOUR_TRANSACTION>.

**Comment by nahern** [comment]
thank you for your feedback, will fix that link and publish.

**Comment by chriswill** [comment]
I was going to file the same issue.

The url provided is exactly what @dgellow says.  However, the correct url would seem to be in the format of 

`https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=<TRANSACTION>`

You can find this url by getting your transaction ID, going to the explorer main page, and pasting it into the search box.  This is the URL that the explorer creates.
