### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

### ISSUE THREAD

**Issue by AlleycatStudios** [cardano-foundation/testnets-cardano-org#474]
**Where does the issue occur?**
On this page, when installing GHC:
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

**Describe the issue**
The last instruction for installing GHC "sudo yum install ncurses-compat-libs" appears to be the CentOS syntax.  I am getting an error trying to set up a node on Ubuntu

**Expected changes**
Provide correct syntax for both versions of Linux

**Additional context**

**Comment by nahern** [comment]
thank you for your feedback, we will update this section.

**Comment by nahern** [comment]
Hi @CarlosLopezDeLara - do you know the syntax we need here for Ubuntu?

**Comment by olgahryniuk** [comment]
Please see updated details here > https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md/
