### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by ahmedjolani** [cardano-foundation/testnets-cardano-org#479]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

**Describe the issue**
I am using Ubuntu 20.04.2 LTS and trying to run this command:
nix-build -A scripts.testnet.node -o testnet-node

I am getting this:
`~/cardano-node$ nix-build -A scripts.testnet.node -o testnet-node-local
trace: To make project.plan-nix for cardano-node-src a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for cardano-node-src entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
error: while setting up the build environment: getting attributes of path '': No such file or directory
(use '--show-trace' to show detailed location information)`

**Expected changes**
Troubleshooting instructions or fixed command. Currently, I am not able to build the testnet locally.

**Additional context**
You might wanna check the nix.conf content in that page as well.

**Comment by ahmedjolani** [comment]
Similar issue: https://github.com/input-output-hk/cardano-node/issues/2356

Also, I'd like to report that this line `./ff-node-local` should be `./testnet-node`.

**Comment by ahmedjolani** [comment]
Also, in some other places of the doc you mention that NIX is no longer supported. Please update your guide accordingly.

```
...
Note: We no longer provide supported stack or nix installer packages. We recommend cabal instead.
...
```

The previous statement is mentioned here: https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html

**Comment by RedToasty** [comment]
Although it's probably a bit late, the issue is just on the formatting of the nix.conf, it just needs flagging as code, I've posted a solution in another Issue report.

**Comment by olgahryniuk** [comment]
Thank you for your input. The updated instructions can be found here > https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/building-the-node-using-nix.md/
