### ISSUE TITLE
Invalid content /en/development-environments/native-tokens/faq/

### ISSUE THREAD

**Issue by Rudoww** [cardano-foundation/testnets-cardano-org#480]
**Where does the issue occur?**
https://developers.cardano.org/en/development-environments/native-tokens/faq/

**Describe the issue**
1. On the page listed above, under section **"Min-Ada-Value explanation"**, there seems to be an extra word in the following sentence: "including **ad** Ada is a limited resource". I have attached a screenshot for reference.

<img width="826" alt="Cardano doc - Issue1" src="https://user-images.githubusercontent.com/52272454/108038589-ffcc5d80-7075-11eb-8bdf-1db27480693b.png">

2. Throughout the page, the word "ada" has the first letter in uppercase and sometimes not.
3. Code snippet #7 under **Example: Minting A New Native Asset** is referencing the mainnet. I have attached a screenshot for reference.
<img width="851" alt="Cardano doc - Issue3" src="https://user-images.githubusercontent.com/52272454/108040691-969a1980-7078-11eb-8d7c-5a77b6e50ddf.png">

**Expected changes**
1. I believe the word **ad** should be removed from the sentence.
2. The word "ada" should either be written as "Ada" or "ada" throughout the page for better consistency; unless this has been intentional, then please ignore this second comment.
3. The code should replace "--mainnet" with "--network-magic 3".

**Additional context**
N/A.

**Comment by nahern** [comment]
@fsancheziohk could you take a look at this and amend please, remove `ad` and change `Ada` to `ada`.

**Comment by nahern** [comment]
this page has been updated and issues resolved.
