### ISSUE TITLE
Error ff-node-local: No such file or directory when building test node via nix in the documentation

### ISSUE THREAD

**Issue by jochasinga** [cardano-foundation/testnets-cardano-org#484]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

Please see the [screenshot](https://imgur.com/a/28ewTL1).

**Describe the issue**

Building the node with the command in the doc:

`nix-build -A scripts.testnet.node -o testnet-node ./ff-node-local`

This error was returned:

`error: getting status of '$HOME/cardano-node/ff-node-local': No such file or directory`

**Expected changes**

If it is outdated, an updated command to build the test node based on the latest release.
Else a more clear explanation of the errors expected, for example, the naming convention of 
`ff-node-local` should be more clear to reflect whether the directory is created automatically
by the build command or must be explicitly created by the user.

**Other context**
Trying to run:
`nix-build -A scripts.testnet.node -o testnet-node .`

(Using `.` instead of `./ff-node-local`)

This error was returned:

```bash

trace: To make project.plan-nix for cardano-node-src a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for cardano-node-src entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
error: while setting up the build environment: getting attributes of path '': No such file or directory

```

**Comment by olgahryniuk** [comment]
Please updated details here > https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/building-the-node-using-nix.md/
