### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by dungnha** [cardano-foundation/testnets-cardano-org#485]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

**Describe the issue**
wget https://downloads.haskell.org/~ghc/8.6.5/ghc-8.6.5-x86_64-deb9-linux.tar.xz
tar -xf ghc-8.6.5-x86_64-deb9-linux.tar.xz
rm ghc-8.6.5-x86_64-deb9-linux.tar.xz
cd ghc-8.6.5

**Expected changes**
8.6.5 -> 8.10.2

**Additional context**

**Comment by nahern** [comment]
@CarlosLopezDeLara should this be amended to 8.10.2?

**Comment by olgahryniuk** [comment]
Please see updated tutorials here > https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md/
