### ISSUE TITLE
Invalid content /en/programming-languages/glow/getting-started/glow-test-network/

### ISSUE THREAD

**Issue by soccer193** [cardano-foundation/testnets-cardano-org#516]
**Where does the issue occur?**
```
git clone https://github.com/fare/gerbil-ethereum.git
cd gerbil-ethereum
./scripts/run-ethereum-test-net.ss
```

**Describe the issue**
The run ethereum testnet script fails to start.
```
> ./scripts/run-ethereum-test-net.ss
*** ERROR IN gx#core-expand-import%__% -- Syntax Error
*** ERROR IN "scripts/run-ethereum-test-net.ss"@13.3
--- Syntax Error: Cannot find library module
... form:   :clan/base
>
```

**Expected changes**
It was enough to run 
`for i in github.com/fare/gerbil-utils github.com/fare/gerbil-crypto github.com/fare/gerbil-poo github.com/fare/gerbil-persist ; do gxpkg install $i ; done`, as was suggested in the file `gerbil-ethereum/build.ss`, before running the script, in order to fix our problem. Though, this might be overkill and could be achieved with a shorter command.

**Comment by olgahryniuk** [comment]
Thank you for raising this issue and sorry for the delay in response. If you're still interested in working with Glow, please consider reaching out to MuKn directly > https://glow-lang.org/
