### ISSUE TITLE
Invalid content /en/development-environments/native-tokens/working-with-multi-asset-tokens/

### ISSUE THREAD

**Issue by haskell-monad** [cardano-foundation/testnets-cardano-org#518]
**Where does the issue occur?**
[article](https://developers.cardano.org/en/development-environments/native-tokens/working-with-multi-asset-tokens/)

* `6. Fund the address and check again`
* `7. Export the protocol parameters to a file for later use`

**Describe the issue**

6: 
  * I want to know how to `Fund the address`? can you give detailed commands and parameters in this example?

7:
```shell
cardano-cli  query protocol-parameters \
--mainnet \
--out-file protocol.json
```

in this example, should it be:?
```shell
cardano-cli  query protocol-parameters \
--testnet-magic 3 --mary-era\
--out-file protocol.json
```

**Comment by olgahryniuk** [comment]
Native token functionality is now live on mainnet. Please see updated tutorials here > https://developers.cardano.org/docs/native-tokens/
