### ISSUE TITLE
Invalid content /en/development-environments/native-tokens/how-to-use-multi-asset-tokens-in-the-cardano-node/

### ISSUE THREAD

**Issue by dgellow** [cardano-foundation/testnets-cardano-org#519]
**Where does the issue occur?**

https://developers.cardano.org/en/development-environments/native-tokens/how-to-use-multi-asset-tokens-in-the-cardano-node/

![image](https://user-images.githubusercontent.com/2451004/109530442-02d43e80-7ab7-11eb-8901-ef3bf2f9141d.png)

**Describe the issue**
The name of the cardano-node image on docker hub is `inputoutput/cardano-node` and not `input-output/cardano-node`.

**Expected changes**

The correct name is being used in the documentation.

**Additional context**

On docker hub:

https://hub.docker.com/r/inputoutput/cardano-node

![image](https://user-images.githubusercontent.com/2451004/109530598-2dbe9280-7ab7-11eb-8495-66a2cfe4fd93.png)

**Comment by nahern** [comment]
@fsancheziohk can you amend this please
