### ISSUE TITLE
Ungültiger Inhalt /de/testnets/cardano/übersicht/

### ISSUE THREAD

**Issue by TechnoDoc88** [cardano-foundation/testnets-cardano-org#520]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by nahern** [comment]
hi TechnoDoc88, can you please provide more details, what is the issue and where does it occur?

**Comment by olgahryniuk** [comment]
Closing due to lack of details
