### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by RedToasty** [cardano-foundation/testnets-cardano-org#528]
**Where does the issue occur?**
In the part listing the contents of nix.conf

**Describe the issue**
The example nix.conf won't work in it's current state, it needs flagging as code to be correctly newlined.

**Expected changes**
The contents should read:

extra-sandbox-paths = /etc/nsswitch.conf /etc/protocols
substituters = https://iohk.cachix.org https://hercules-ci.cachix.org https://cache.nixos.org/ https://cache.nixos.org https://hydra.iohk.io https://cache.nixos.org/
trusted-substituters = 
trusted-public-keys = iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= hercules-ci.cachix.org-1:ZZeDl9Va+xe9j+KqdzoBZMFJHVQ42Uu/c/1/KMC5Lw0= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

Having it all as 1 single block breaks the parameters.

**Additional context**

**Comment by olgahryniuk** [comment]
Thanks for your feedback! The page has been updated referencing to >> https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/building-the-node-using-nix.md/
