### ISSUE TITLE
Invalid content /en/programming-languages/glow/getting-started/glow-install/

### ISSUE THREAD

**Issue by applesmash** [cardano-foundation/testnets-cardano-org#529]
**Where does the issue occur?**
In the install documents - need to add a pre-req for RAM requirements.

**Describe the issue**
Attempted to install multiple times with a 2GB RAM VM and it failed at random parts of the build process. Noticed very high resource usage. Upped to 4 GB of RAM and it installed perfectly. 

**Expected changes**
Add a pre-req of "requires 4 GB RAM". 

**Additional context**
Doing my part to help out

**Comment by nahern** [comment]
@elviejo79 can you please update the memory recommendations.

**Comment by olgahryniuk** [comment]
Sorry for the delay in response. If you're still interested in working with Glow, please consider reaching out to MuKn directly > https://glow-lang.org/
