### ISSUE TITLE
Incorrect Faucet URL Example

### ISSUE THREAD

**Issue by craigem** [cardano-foundation/testnets-cardano-org#532]
**Where does the issue occur?**
[The Cardano Testnet Faucet](https://developers.cardano.org/en/testnets/cardano/about/the-testnet-faucet/)

**Describe the issue**
Incorrect URL in example code:
```
curl -v -XPOST "https://faucet.cardano-testnet.iohk.io/send-money/$YOURADDRESS?apiKey=$APIKEY"
```

**Expected changes**
Should be:
```
curl -v -XPOST "https://faucet.cardano-testnet.iohkdev.io/send-money/$YOURADDRESS?apiKey=$APIKEY"
```

**Additional context**
None.

**Comment by james-iohk** [comment]
Do we need this page when there is [Faucet](https://developers.cardano.org/en/testnets/cardano/tools/faucet/)?
It also doesn't mention Native Token support.

**Comment by johnalotoski** [comment]
Incorrect URL and faucet return address now corrected.

**Comment by nahern** [comment]
thanks @johnalotoski
