### ISSUE TITLE
Invalid content /en/virtual-machines/kevm/overview/ - smart contract doesn't return hello world

### ISSUE THREAD

**Issue by truedat101** [cardano-foundation/testnets-cardano-org#535]
**Where does the issue occur?**
https://developers.cardano.org/en/virtual-machines/kevm/getting-started/mallet-end-to-end/

**Describe the issue**
When deploying and running the smart contract, the smart contract does not return HelloWorld.

**Expected changes**

If there is the possibility for a failure in this most simple smart contract demo, it would be good to provide some troubleshooting section .  I actually don't have a clue why the smart contract returns "" when I invoke it.

**Additional context**
Would love to know why  the magic failed.

**Comment by yubi420** [comment]
https://github.com/cardano-foundation/testnets-cardano-org/issues/488

Same issue here.

**Comment by cleisthenes-alpha** [comment]
Hi - I'm following the other thread (#488) and thought I'd share [my fix](https://github.com/cardano-foundation/testnets-cardano-org/issues/488#issuecomment-795907372) here as well. Can you let me know if this helps?

**Comment by truedat101** [comment]
Yeah, we should close this one and jump to the other thread to track this.
