### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/creating-a-stake-pool/

### ISSUE THREAD

**Issue by rogervs** [cardano-foundation/testnets-cardano-org#543]
**Where does the issue occur?**
```
Prerequisites for stake pool operators

As a stake pool operator for Cardano, you will typically have the following abilities: *operational knowledge of how to set up, run and maintain a Cardano <name> node continuously
```

**Describe the issue**
`<name>` seems out of place

**Expected changes**
Expect `<name>` not to be there

**Additional context**
None

**Comment by nahern** [comment]
thank you for your feedback, https://github.com/cardano-foundation/testnets-cardano-org/pull/545 has been created to fix this.
