### ISSUE TITLE
Invalid content /en/programming-languages/glow/getting-started/glow-tutorial/deadman-switch/

### ISSUE THREAD

**Issue by olivbau** [cardano-foundation/testnets-cardano-org#546]
**Where does the issue occur?**
In this page : https://developers.cardano.org/en/programming-languages/glow/getting-started/glow-tutorial/deadman-switch/
There is a problem with this image : https://ucarecdn.com/8b0ba880-443f-4b43-991d-ed5ac2dd2350/deadmanswitch.png

**Describe the issue**
The image title is incorrect

**Expected changes**
Update title from Rock, Paper, Scissors to Deadman Switch

**Comment by nahern** [comment]
@elviejo79 could you take a look please

**Comment by joeldavuk** [comment]
The actual sequence diagram is wrong also

**Comment by olgahryniuk** [comment]
Sorry for the delay in response. IOG is currently not working with the Glow team. Please consider reaching out to MuKn directly > https://glow-lang.org/
