### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/what-is-a-cardano-node/

### ISSUE THREAD

**Issue by Squiji** [cardano-foundation/testnets-cardano-org#548]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/

**Describe the issue**
In 'Supported Platforms' link, would be helpful to mention minimum system specs for individuals.

**Comment by olgahryniuk** [comment]
Thank you for your feedback, we will look into this!
