### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by okeddie** [cardano-foundation/testnets-cardano-org#551]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

**Describe the issue**
an apt dependacy list 'like installer "this needs rsync and curl"

**Expected changes**
a debian based list of pre-reqs for packages

**Additional context**
-

**Comment by olgahryniuk** [comment]
This page has been updated referencing to the following instructions:
https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/building-the-node-using-nix.md/
