### ISSUE TITLE
Invalid content /en/programming-languages/glow/getting-started/glow-tutorial/deadman-switch/

### ISSUE THREAD

**Issue by joeldavuk** [cardano-foundation/testnets-cardano-org#556]
**Where does the issue occur?**
https://developers.cardano.org/en/programming-languages/glow/getting-started/glow-tutorial/deadman-switch/

**Describe the issue**
Miss-spelling of uncle "millionaire unlce" is used in the opening paragraph

**Expected changes**
Correct spelling on uncle

**Additional context**
N/A

**Comment by olgahryniuk** [comment]
Thank you, we are now updating the copy.
