### ISSUE TITLE
Invalid content /en/programming-languages/marlowe/getting-started/using-the-marlowe-playground/

### ISSUE THREAD

**Issue by platanero** [cardano-foundation/testnets-cardano-org#565]
**Where does the issue occur?**
When you click through the Online Tutorial link, you get a 404 error:
https://alpha.marlowe.iohkdev.io/tutorial/index.html

**Describe the issue**
Screenshot of error:
![image](https://user-images.githubusercontent.com/3686261/115090676-7d301500-9ee3-11eb-90d2-3d059e25b013.png)

**Expected changes**
Fix the link.

**Comment by olgahryniuk** [comment]
Thank you! The link has been fixed.
