### ISSUE TITLE
Invalid content /en/programming-languages/plutus/getting-started/

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [cardano-foundation/testnets-cardano-org#566]
**Where does the issue occur?**
The links at the top of the page - https://developers.cardano.org/en/programming-languages/plutus/getting-started/

**Describe the issue**
https://docs.cardano.org/projects/plutus/en/latest/tutorials/plutus-playground.html => NOT_FOUND
https://docs.cardano.org/projects/plutus/en/latest/tutorials/basic-apps.html => NOT FOUND

**Expected changes**
Replace the links with working ones.

**Additional context**

**Comment by olgahryniuk** [comment]
Thank you! These links have been fixed.
