### ISSUE TITLE
Invalid content /en/programming-languages/plutus/getting-started/

### ISSUE THREAD

**Issue by sampa999** [cardano-foundation/testnets-cardano-org#571]
**Where does the issue occur?**
https://developers.cardano.org/en/programming-languages/plutus/getting-started/

**Describe the issue**
These 2 links are broken
Compiling and testing a Plutus App in the Plutus Playground
https://docs.cardano.org/projects/plutus/en/latest/tutorials/plutus-playground.html
Writing a basic Plutus app in the Plutus Playground
https://docs.cardano.org/projects/plutus/en/latest/tutorials/basic-apps.html

**Expected changes**
They should link to the expected tutorials

**Additional context**

**Comment by olgahryniuk** [comment]
Thank you! These links have been fixed.
