### ISSUE TITLE
Invalid content /en/development-environments/native-tokens/native-tokens/

### ISSUE THREAD

**Issue by Bez625** [cardano-foundation/testnets-cardano-org#573]
**Where does the issue occur?**
https://developers.cardano.org/en/development-environments/native-tokens/native-tokens/

**Describe the issue**
The page https://developers.cardano.org/en/development-environments/native-tokens/native-tokens/ seems to be available intermittently e.g. today I have seen:
![Screenshot from 2021-04-28 10-17-24](https://user-images.githubusercontent.com/4602753/116379513-fba58480-a80a-11eb-987b-00742af958ca.png)

and:
![Screenshot from 2021-04-28 10-17-11](https://user-images.githubusercontent.com/4602753/116379527-fea07500-a80a-11eb-86b1-a68823fec349.png)

**Expected changes**
This page is referenced in multiple places as a resource to create Native Tokens and should be available consistently.

**Additional context**
Example blog post referencing the intermittently available webpage https://iohk.io/en/blog/posts/2020/12/09/native-tokens-on-cardano-core-principles-and-points-of-difference/

**Comment by nahern** [comment]
thanks for your feedback, the content for native tokens has moved to our documentation site [Cardano Docs](https://docs.cardano.org/en/latest/native-tokens/learn-about-native-tokens.html), as native tokens are now on mainnet. Prior to this content was on the developer site as it was in a testing phase. The blog was released when native tokens was being testing.

**Comment by Bez625** [comment]
Thanks @nahern - would it be possible to put a link on this page to the correct documentation? That would probably help a lot of people that found themselves in my position being directed to a stale page
