### ISSUE TITLE
Invalid content /en/programming-languages/marlowe/getting-started/sample-marlowe-smart-contracts/

### ISSUE THREAD

**Issue by alno04140** [cardano-foundation/testnets-cardano-org#576]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment]
Unfortunately, you haven't provided any details about the issue. Broken links have been fixed though. Thank you!
