### ISSUE TITLE
E: Unable to locate package ncurses-compat-libs

### ISSUE THREAD

**Issue by msapra85** [cardano-foundation/testnets-cardano-org#577]
**Where does the issue occur?**
On the page:
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/
Under section:
Downloading And Installing GHC
At: sudo yum install ncurses-compat-libs

**Describe the issue**
upon running the above mentioned sudo command, I see the following error:

rookie101@rebelPC:~/cardano/ghc-8.6.5$ sudo yum install ncurses-compat-libs
sudo: yum: command not found

Therefore, trying apt:
rookie101@rebelPC: ~/cardano/ghc-8.6.5$ sudo apt install ncurses-compat-libs
Reading package lists. Done
Building dependency tree
Reading state information. Done
**E: Unable to locate package ncurses-compat-libs**
rookie101@rebelPC: ~/cardano/ghc-8.6.5$

**Expected changes**
should've completed without any issue.

**Additional context**

**Comment by olgahryniuk** [comment]
The page has been updated. Please see the references to developer repositories: https://testnets.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/
