### ISSUE TITLE
Invalid content /en/programming-languages/marlowe/getting-started/sample-marlowe-smart-contracts/

### ISSUE THREAD

**Issue by RyanJulyan** [cardano-foundation/testnets-cardano-org#585]
**Where does the issue occur?**
https://developers.cardano.org/en/programming-languages/marlowe/getting-started/sample-marlowe-smart-contracts/

The online tutorial has the example of an Escrow contract section 3

The link for section 3

**Describe the issue**
The link leads to a broken link: https://alpha.marlowe.iohkdev.io/tutorial/index.html#escrow-ex

**Expected changes**
Update the link to a working example

**Additional context**
This was my first interaction with the docs and the platform and the link was broken. Other reading said smart contracts are not ready, so this makes me worry as someone new to the platform.

**Comment by olgahryniuk** [comment]
Thank you for raising this issue. The links have been fixed
