### ISSUE TITLE
Invalid content /en/programming-languages/plutus/overview/

### ISSUE THREAD

**Issue by julimax** [cardano-foundation/testnets-cardano-org#586]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment]
Links to tutorials have been updated
