### ISSUE TITLE
Invalid content /en/programming-languages/plutus/getting-started/

### ISSUE THREAD

**Issue by anibalvelarde** [cardano-foundation/testnets-cardano-org#605]
**Where does the issue occur?**
The [Getting Started](https://developers.cardano.org/en/programming-languages/plutus/getting-started/) page.

**Describe the issue**
Said page, contains 2 links that, when the user clicks on them, they lead me to a `404 HTTP` error code. The links are:
* Compiling and testing a Plutus App in the Plutus Playground
* Writing a basic Plutus app in the Plutus Playground

**Expected changes**
It'd be great if the user could get to the link and be able to work the tutorials.

**Additional context**
No additional context is available at this time.

**Comment by olgahryniuk** [comment]
Thank you! These links have been updated
