### ISSUE TITLE
Invalid content /en/programming-languages/plutus/resources/

### ISSUE THREAD

**Issue by LiboShen** [cardano-foundation/testnets-cardano-org#608]
**Where does the issue occur?**
https://developers.cardano.org/en/programming-languages/plutus/resources/

**Describe the issue**
"Plutus Tutorials" and "Plutus Glossary" lins are broken. Got 404 page.

**Expected changes**
Should document page with content.

**Additional context**

**Comment by olgahryniuk** [comment]
These issues have been addressed. Thank you
