### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-using-nix/

### ISSUE THREAD

**Issue by asmckinlay** [cardano-foundation/testnets-cardano-org#609]
**Where does the issue occur?**
Section with the commands:
```
git clone https://github.com/input-output-hk/cardano-node
cd cardano-node
nix-build -A scripts.testnet.node -o testnet-node
./ff-node-local
```

**Describe the issue**
After running the command `nix-build -A scripts.testnet.node -o testnet-node` then the command
`./ff-node-local`, it turns out there is `no such file or directory: ./ff-node-local` in the `cardano-node` directory or the `cardano-node/cardano-node` directory

**Expected changes**
Documentation update

**Additional context**
As an engineer, I'm looking to set up my own private staking pool.
I'm running on macOS Big Sur V11.4, Apple M1 processor

**Comment by olgahryniuk** [comment]
Please see these instructions and raise an issue with a development team:
https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/building-the-node-using-nix.md/
