### ISSUE TITLE
Invalid content /en/programming-languages/glow/getting-started/glow-tutorial/deadman-switch/

### ISSUE THREAD

**Issue by bezerrablockchain** [cardano-foundation/testnets-cardano-org#610]
**Where does the issue occur?**
https://developers.cardano.org/en/programming-languages/glow/getting-started/glow-tutorial/deadman-switch/

**Describe the issue**
In the deadman contract picture, it seems to be mixed with last example, the Rock, Paper, Scissors 

**Expected changes**
All the no related deadman contract should be cut of the picture
![image](https://user-images.githubusercontent.com/85590173/123848672-f84f7780-d8e5-11eb-87d4-ec56f1ee6a84.png)

**Additional context**

**Comment by olgahryniuk** [comment]
Sorry for the delay in response. IOG is currently not working with the Glow team. Please consider reaching out to MuKn directly > https://glow-lang.org/
