### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by retrocoder68** [cardano-foundation/testnets-cardano-org#611]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

**Describe the issue**
In the last paragraph the link "installing from source instructions" leads to a 404 page.

**Expected changes**
Correct broken link

**Additional context**

**Comment by olgahryniuk** [comment]
These pages have been updated. Thank you for your feedback
