### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/configuring-a-node-using-yaml/

### ISSUE THREAD

**Issue by RealMathamyeli** [cardano-foundation/testnets-cardano-org#612]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

https://developers.cardano.org/en/testnets/cardano/get-started/configuring-a-node-using-yaml/

https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/understanding-config-files.html#the-topology-json-file

**Describe the issue**
If I click on the "topology file" link I get redirected to an error 404 page.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment]
The link seems to be working now. Please see this source for details: https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/understanding-config-files.md/#the-genesisjson-file
