### ISSUE TITLE
Invalid content /en/programming-languages/plutus/getting-started/

### ISSUE THREAD

**Issue by nbmoa** [cardano-foundation/testnets-cardano-org#615]
**Where does the issue occur?**
https://developers.cardano.org/en/programming-languages/plutus/getting-started/

**Describe the issue** 
Links are broken (404)

**Expected changes**
New locations (I guess)
https://plutus.readthedocs.io/en/latest/plutus/tutorials/plutus-playground.html
https://docs.cardano.org/projects/plutus/en/latest/plutus/tutorials/basic-apps.html

**Comment by olgahryniuk** [comment]
Thanks for your feedback! These links have been fixed
