### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/creating-a-stake-pool/

### ISSUE THREAD

**Issue by HOPU** [cardano-foundation/testnets-cardano-org#616]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

A link is not working to the register a pool.

**Describe the issue**
A clear and concise description of what the issue is.

This link is not working:
https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/register_stakepool.html#generate-stake-pool-registration-certificate

**Expected changes**
A clear and concise description of what you expected to change.
Link it properly.

**Additional context**

**Comment by olgahryniuk** [comment]
Thanks for your feedback! #734 addresses this issue
