### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/creating-a-stake-pool/

### ISSUE THREAD

**Issue by GuusKolpa** [cardano-foundation/testnets-cardano-org#620]
**Where does the issue occur?**
https://developers.cardano.org/en/testnets/cardano/get-started/creating-a-stake-pool/

Link is broken in documentation on page 'Creating A Stake Pool'. Link should point to an example of an operational certificate generation. 

Broken link is: 
https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/node_keys.html#generate-the-operational-certificate

Returns 404.

![image](https://user-images.githubusercontent.com/52562907/124828662-db671400-df77-11eb-9599-9558949f106b.png)

**Comment by olgahryniuk** [comment]
Thanks for your feedback! #734 addresses this issue.
