### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/building-the-node-from-source/

### ISSUE THREAD

**Issue by msapra85** [cardano-foundation/testnets-cardano-org#623]
**Where does the issue occur?**
https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html.

**Describe the issue**
Page doesn’t exist. Error 404

**Expected changes**
Should open page  from where one can refer node installation guide

**Additional context**

**Comment by olgahryniuk** [comment]
The page has been updated, please see references here: https://docs.cardano.org/getting-started/installing-the-cardano-node
