### ISSUE TITLE
Invalid content https://cardano.org/calculator/?calculator=operator

### ISSUE THREAD

**Issue by MarkStepp** [cardano-foundation/testnets-cardano-org#625]
**Where does the issue occur?**
From this page:  `https://cardano.org/calculator/?calculator=operator`
click on "Developers" > "Marlowe Playground"

**Describe the issue**
links to this page:   `https://testnets.cardano.org/en/marlowe/overview/`
"Page Not Found"

**Expected changes**
I think the link should go here: `https://alpha.marlowe.iohkdev.io/#/ `
or
here:   `https://testnets.cardano.org/en/programming-languages/marlowe/overview/ `

**Additional context**

**Comment by olgahryniuk** [comment]
The link works now. Thanks for raising this issue
