### ISSUE TITLE
 Invalid address to hkp://pool.sks-keyservers.net --search-keys signing.authority@iohk.io

### ISSUE THREAD

**Issue by guarinel** [cardano-foundation/testnets-cardano-org#628]
**Where does the issue occur?**
Broken link from https://testnets.cardano.org/en/testnets/cardano/get-started/wallet/ (verify signature Linux) 

**Describe the issue**
The shell command gpg2 --keyserver hkp://pool.sks-keyservers.net --search-keys signing.authority@iohk.io is not working. Address is empty.

**Expected changes**
Correct command should be gpg2 --keyserver hkp://Keys.Openpgp.org --search-keys signing.authority@iohk.io .

**Comment by olgahryniuk** [comment]
@alexghr will you please take a look at this?
