### ISSUE TITLE
Invalid content /en/testnets/alonzo-testnet/

### ISSUE THREAD

**Issue by Spiderwriter** [cardano-foundation/testnets-cardano-org#632]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by Spiderwriter** [comment]
The copy reads 'We have recently launched...' but the entry is not dated. It should be phrased 'On xx of yyuray 2021...'

**Comment by olgahryniuk** [comment]
Thanks for your input.
