### ISSUE TITLE
Invalid content /en/virtual-machines/welcome/

### ISSUE THREAD

**Issue by ytiv** [cardano-foundation/testnets-cardano-org#634]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by ytiv** [comment]
I've lost some Crypto 
Can you guys help me out?
btw we love ADA!

**Comment by olgahryniuk** [comment]
:)
