### ISSUE TITLE
Invalid content /en/programming-languages/plutus/resources/

### ISSUE THREAD

**Issue by alazzawimahmoud** [cardano-foundation/testnets-cardano-org#635]
**Where does the issue occur?**
https://testnets.cardano.org/en/programming-languages/plutus/resources/

**Describe the issue**
The link to `Plutus Glossary` is not correct.

**Expected changes**
The link to `Plutus Glossary` should be `https://docs.cardano.org/glossary`

**Comment by olgahryniuk** [comment]
Thanks for your feedback, the link has been fixed.
