### ISSUE TITLE
Invalid content /en/programming-languages/glow/getting-started/glow-test-network/

### ISSUE THREAD

**Issue by jimmycw74** [cardano-foundation/testnets-cardano-org#638]
**Where does the issue occur?**
At the sentence : "Alice would add Alice’s address to her contact list with a command as follows:" 

**Describe the issue**
This is wrong, should be: Bob would Alice's...

**Expected changes**
The correct sentence should be: "Bob would add Alice’s address to her contact list with a command as follows:"

**Comment by olgahryniuk** [comment]
This is now updated, thank you.
