### ISSUE TITLE
Invalid content /en/testnets/cardano/tools/faucet/

### ISSUE THREAD

**Issue by nirmalsingh** [cardano-foundation/testnets-cardano-org#645]
**Where does the issue occur?**
At web-page with below URL :
https://testnets.cardano.org/en/testnets/cardano/tools/faucet/

**Describe the issue**
GUI Text fields, Button to facilitate sending of Test Ada to any wallet address is not visible on the page anymore.

**Expected changes**
GUI Text fields, Button to facilitate sending of Test Ada to any wallet address must be visible on the page.

**Additional context**
I tried with multiple Laptops, Browsers but same issue. In-fact, I checked with other forum users and its same state for them too. forum URL pasted below.

https://forum.cardano.org/t/is-there-really-any-working-frontend-web-page-of-testnet-faucet/71077

**Comment by kraymond37** [comment]
The same issue. Today the request form appears, but it returns server error. 
There was one request success, but the tx could not be found in testnet explorer. 
My address is an enterprise address, I don't know if it matters.

**Comment by nirmalsingh** [comment]
Today request form appeared for me too, However threw below error , not sure if its valid expected error. will try again at said time.

Too many requests, retry after September 3, 2021 4:43 PM

**Comment by nirmalsingh** [comment]
> The same issue. Today the request form appears, but it returns server error.
> There was one request success, but the tx could not be found in testnet explorer.
> My address is an enterprise address, I don't know if it matters.

try with base address of your wallet.

**Comment by nirmalsingh** [comment]
A different issue today, throwing "server error".

**Comment by teodoryantcheff** [comment]
`502`s on faucet. 

Using the GUI results in 

![Selection_474](https://user-images.githubusercontent.com/4791195/132120886-3f9a41ce-e9c5-4e23-8c92-2cd9022eca6d.png)

```
teo@thinkpad:~/.local$ curl -v -XPOST "https://faucet.cardano-testnet.iohkdev.io/send-money/addr_test1qquudwrml4ghlaz6hmdmequf8r8c40hrn7926pgsyv7l4uyka8rwas5g2fc6rz8325sdwj5y3cp9at2gye6dpr5j88jqdnhajy"
*   Trying 3.64.141.89:443...
* TCP_NODELAY set
* Connected to faucet.cardano-testnet.iohkdev.io (3.64.141.89) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=faucet.cardano-testnet.iohkdev.io
*  start date: Jul 11 16:55:51 2021 GMT
*  expire date: Oct  9 16:55:50 2021 GMT
*  subjectAltName: host "faucet.cardano-testnet.iohkdev.io" matched cert's "faucet.cardano-testnet.iohkdev.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x564d6efebe10)
> POST /send-money/addr_test1qquudwrml4ghlaz6hmdmequf8r8c40hrn7926pgsyv7l4uyka8rwas5g2fc6rz8325sdwj5y3cp9at2gye6dpr5j88jqdnhajy HTTP/2
> Host: faucet.cardano-testnet.iohkdev.io
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 502 
< server: nginx
< date: Sun, 05 Sep 2021 08:40:09 GMT
< content-type: text/html
< content-length: 150
< vary: Origin
< access-control-allow-methods: POST, OPTIONS
< access-control-allow-headers: User-Agent,X-Requested-With,Content-Type
< 
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host faucet.cardano-testnet.iohkdev.io left intact
teo@thinkpad:~/.local$ 

```

**Comment by kraymond37** [comment]
I contacted the IOHK Technical Service Desk. They said they had a temporary server issue on Testnet faucet and it was fixed now.

**Comment by teodoryantcheff** [comment]
Yep, seems to be working now. Thanks!

**Comment by olgahryniuk** [comment]
Thanks for sharing your feedback! The faucet is working and you can request tADA when needed.
