### ISSUE TITLE
Invalid content /en/testnets/cardano/tools/faucet/

### ISSUE THREAD

**Issue by iblisjogja** [cardano-foundation/testnets-cardano-org#664]
![Uploading Screenshot_20210905_154958.jpg…]()

1.why error server any request tADA faucet?
2.why i cant swap tADA always transaction failed no suitable collateral.

**Comment by olgahryniuk** [comment]
Thanks for sharing your feedback! The faucet has been fixed and is working well now. The receiving address is also working. In case the issue occurs in testnet Daedalus, please raise an issue with IOHK Support - https://iohk.zendesk.com/hc/en-us
