### ISSUE TITLE
Invalid content /en/testnets/cardano/tools/faucet/

### ISSUE THREAD

**Issue by mikegcoleman** [cardano-foundation/testnets-cardano-org#670]
**Where does the issue occur?**
https://testnets.cardano.org/en/testnets/cardano/tools/faucet/

**Describe the issue**
Attempting to issue either tADA or Testcoin to a testnet address results in a generic "Server Error" message

**Expected changes**
I expect to have the transaction process correctly and send the right coin to the selected address . 

**Additional context**
None.

**Comment by olgahryniuk** [comment]
Thanks for sharing your feedback! The faucet has been fixed and is working well now. The receiving address is also working. In case the issue occurs in testnet Daedalus, please raise an issue with IOHK Support - https://iohk.zendesk.com/hc/en-us
