### ISSUE TITLE
Invalid content /en/programming-languages/plutus/overview/

### ISSUE THREAD

**Issue by tycooperaow** [cardano-foundation/testnets-cardano-org#677]
https://developers.cardano.org/en/programming-languages/plutus/overview/

**decentralised** is supposed to be **decentralized**. There's a misspelling

<img width="752" alt="Screen Shot 2021-10-22 at 15 37 20" src="https://user-images.githubusercontent.com/35544142/138513493-e2351b73-7675-44e4-838d-4c7294efdb5e.png">

**Comment by nahern** [comment]
updated, closing this issue
