### ISSUE TITLE
Invalid content /en/programming-languages/plutus/resources/

### ISSUE THREAD

**Issue by Lootheo** [cardano-foundation/testnets-cardano-org#678]
**Where does the issue occur?**
https://plutus.readthedocs.io/en/latest/plutus/tutorials/index.html
**Describe the issue**
Page of the "Plutus Tutorials" button goes to a non existant page
**Expected changes**
Redirect this to the correct plutus tutorial

**Comment by nahern** [comment]
link is correct, closing this issue
