### ISSUE TITLE
Invalid content /en/programming-languages/plutus/getting-started/

### ISSUE THREAD

**Issue by JstnEdr** [cardano-foundation/testnets-cardano-org#679]
**Where does the issue occur?**
https://testnets.cardano.org/en/programming-languages/plutus/getting-started/

**Describe the issue**
Broken links to tutorials
https://plutus.readthedocs.io/en/latest/plutus/tutorials/plutus-playground.html
https://plutus.readthedocs.io/en/latest/plutus/tutorials/basic-apps.html

**Expected changes**
Would expect the tutorials to be there

**Additional context**

**Comment by olgahryniuk** [comment]
Thanks for your feedback! The links are working now.
