### ISSUE TITLE
Confusing stake pool operation calculator output

### ISSUE THREAD

**Issue by rossettistone** [cardano-foundation/testnets-cardano-org#681]
**Where does the issue occur?**
https://testnets.cardano.org/en/testnets/cardano/tools/staking-calculator/
<img width="847" alt="Screen Shot 2021-11-03 at 8 05 24 AM" src="https://user-images.githubusercontent.com/1834981/140086545-7c006b85-939c-48ca-8bb6-dc837a52f39c.png">

**Describe the issue**
While I'm new to Cardano, the staking calculator gives numbers that are inconsistent with estimates I've seen elsewhere for stake pool operation revenue/rewards. While most estimates I've seen are in the range of 6% APR, the calculator consistently gives numbers in the range of 800% APR.

**Expected changes**
It may be that there's a technical error with the calculator, or it could be that some improvement to the UI or documentation would help me to better understand what the present calculation represents.

**Additional context**
N/A

**Comment by olgahryniuk** [comment]
Thanks for your feedback. This might have been a temporary issue, the calculator gives more accurate estimates now.
