### ISSUE TITLE
The EVM devnet provides a link to the blockchain explorer. Where is the Link

### ISSUE THREAD

**Issue by HamishAndrew** [cardano-foundation/testnets-cardano-org#683]
https://testnets.cardano.org/en/virtual-machines/evm/getting-started/block-explorer/

I'd like the Documentation to be up to date and I'd like the KEVM Faucet to work too ....

I'm getting a Thrown error for requestFunds() ..... and other Mallet Commands

I get this error too ....

mallet> requestFunds(Acc1)
Thrown: 'Faucet error: undefined'

**Comment by olgahryniuk** [comment]
We're closing this issue as the KEVM testnet is currently not supported. If you'd like to get involved with EVM testing, you can request early access to the EVM sidechain alpha testnet by filling out [this form](https://alpha-evm-sidechain.iohk.io/). Check out the EVM sidechain [demo](https://www.youtube.com/watch?v=NFxoi3YItEM) to see a smart contract deployed on testnet. 
Thank you
