### ISSUE TITLE
Invalid content /en/virtual-machines/kevm/getting-started/mallet-end-to-end/ 

### ISSUE THREAD

**Issue by HamishAndrew** [cardano-foundation/testnets-cardano-org#684]
I'm reporting this as a Documentation Issue because the KEVM TestNet Faucet doesn't work as described in the Documentation .....

I have followed the Content till Mallet 2.0 part 4. That might be 2.4. requestFunds()

then I get

mallet> selectAccount(myAccount)
'0x9ceb499218bf4839ad7400751b853dd4f7603ea1'
mallet>
mallet> '0x45402404f51909b640d03f361c742c38d34bb3e7'
'0x45402404f51909b640d03f361c742c38d34bb3e7'
mallet> getBalance()
Thrown:
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/mnt/c/mallet/lib/web3/web3/errors.js:38:16)
    at HttpProvider.send (/mnt/c/mallet/lib/web3/web3/httpprovider.js:102:18)
    at RequestManager.send (/mnt/c/mallet/lib/web3/web3/requestmanager.js:65:32)
    at Eth.send [as getBalance] (/mnt/c/mallet/lib/web3/web3/method.js:145:58)
    at Mallet.getBalance (/mnt/c/mallet/lib/mallet.js:238:26)
mallet>

so the Documentation doesn't reflect how the Mallet KEVM Testnet is working just now ...

Can somebody sort it please.

H

**Comment by 1000arezo** [comment]
[README.md](https://github.com/cardano-foundation/testnets-cardano-org/files/7591448/README.md)

**Comment by olgahryniuk** [comment]
@nahern @elviejo79 can you please take a look at this?

**Comment by olgahryniuk** [comment]
We're closing this issue as the KEVM testnet is currently not supported. If you're interested in EVM functionality, you can request early access to the EVM sidechain alpha testnet, by filling out [this form](https://alpha-evm-sidechain.iohk.io/). Check out the EVM sidechain [demo](https://www.youtube.com/watch?v=NFxoi3YItEM) to see a smart contract deployed on testnet.
