### ISSUE TITLE
Invalid content /en/testnets/cardano/get-started/wallet/

### ISSUE THREAD

**Issue by sunking01** [cardano-foundation/testnets-cardano-org#686]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by sunking01** [comment]
hi

**Comment by olgahryniuk** [comment]
Thanks for raising an issue, but unfortunately there aren't enough details provided. The page mentioned seems to work fine. Closing the issue due to lack of details.
