### ISSUE TITLE
Invalid content /en/testnets/cardano/tools/faucet/

### ISSUE THREAD

**Issue by godaMan** [cardano-foundation/testnets-cardano-org#691]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.https://testnets.cardano.org/en/testnets/cardano/tools/faucet/

**Describe the issue**
A clear and concise description of what the issue is.
The tADA facuet is giving error. It says "I can't process this payment as there are not enough funds available in the wallet. I am missing: coin: 278.209272 tokens: []"
**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment]
Thanks for sharing your feedback! The faucet has been recently fixed and is working well now.
