### ISSUE TITLE
Invalid content /en/programming-languages/marlowe/getting-started/using-the-marlowe-playground/

### ISSUE THREAD

**Issue by MahmoudAlslman** [cardano-foundation/testnets-cardano-org#711]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment]
Closing due to lack of details.
