### ISSUE TITLE
Invalid content /en/testnets/cardano/tools/faucet/

### ISSUE THREAD

**Issue by blueguytr78** [cardano-foundation/testnets-cardano-org#721]
**Where does the issue occur?**
Test token is not working

my wallet : addr_test1qzf83x7slfawyjqy7teuc3eth0vxlhq3w29uksgkqt90j3aa3ameu3x89kl0egwegzjw3jrpj2rteynn8k4ayvp47lrqk4jxvc

metamask wallet: 0x8692A0F021A9168dD7b8c100dBDd0CcfA444C298

**Comment by olgahryniuk** [comment]
Thanks for sharing your feedback! The faucet has been recently fixed and should be working well now.
