### ISSUE TITLE
Invalid content /en/testnets/cardano/tools/staking-calculator/

### ISSUE THREAD

**Issue by Kiwi206** [cardano-foundation/testnets-cardano-org#727]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment]
Thank you for raising the issue, we checked the 'Staking calculator' page and everything seems to work well. Please indicate which content is invalid since this issue does not provide enough details.
