### ISSUE TITLE
Invalid content /en/testnets/cardano/tools/faucet/

### ISSUE THREAD

**Issue by rasterseven** [cardano-foundation/testnets-cardano-org#738]
I've received the coin, now I want to send it back but the amout is not available.
How to handle it?
![test ada send](https://user-images.githubusercontent.com/79218619/170651484-acecccdc-d49e-4bd3-b1fe-fae861974031.jpg)

**Comment by olgahryniuk** [comment]
Hi @rasterseven 
That's probably because of the transaction fee. Please try sending back a smaller amount of ada.
