### ISSUE TITLE
Adding ImperatorLang to programming languages

### ISSUE THREAD

**Issue by nielstron** [cardano-foundation/testnets-cardano-org#744]
I would like to suggest to add the language Imperator (https://github.com/ImperatorLang/imperator) to the "Programming Languages" tab on testnets.cardano.org. I am open to writing some text, an overview etc about it, just would like to hear about the opinion of the maintainers first.

**Comment by olgahryniuk** [comment]
Hi @nielstron 
Can you please provide the exact issue you're facing?

**Comment by nielstron** [comment]
Hi sorry there was supposed to be a description. I updated the description now.

**Comment by olgahryniuk** [comment]
Thanks for the details @nielstron 
Considering that your project is in development, it might not yet be the right timing to add it to Cardano testnets. I'd suggest we discuss this later again, and I'll also ask for opinions from our development teams. One of the options would be to link to your repository from some community section (e.g. 'Community content' as we have for Cardano). This also means that we'll need to create such a section within 'Programming languages'.

**Comment by olgahryniuk** [comment]
Hello, @nielstron! We'd suggest adding an article about the Imperator programming language and the opportunities it brings to Cardano to the Essential Cardano website (https://www.essentialcardano.io/). This site is a community-driven resource where you can contribute and add more information about all things Cardano :) Hope to see your contribution there soon! Thank you.
