### ISSUE TITLE
Faucet don't adapted to work with preview testnet /en/testnets/cardano/tools/faucet/

### ISSUE THREAD

**Issue by jacfeth** [cardano-foundation/testnets-cardano-org#761]
**Where does the issue occur?**
Link to the file or location on the website where the issue occurs. Optionally add screenshots for context.

**Describe the issue**
A clear and concise description of what the issue is.

**Expected changes**
A clear and concise description of what you expected to change.

**Additional context**

**Comment by olgahryniuk** [comment]
Please find an updated faucet for preview and pre-production here:
https://docs.cardano.org/cardano-testnet/tools/faucet
